### ISSUE TITLE
crates.io release?

### ISSUE THREAD

**Issue by p--b** [aikalant/capnp_conv#1]
Thanks for this code, we find it very useful and are successfully using it in production.

I was wondering if you would consider releasing it on crates.io ? At the moment we bring this in via a git dependency of a private clone, but would much rather be using a "released" version, even if that was a 0.x release for the foreseeable.

Thanks :)

**Comment by aikalant** [comment]
It's definitely on my list.

We upgraded to the new GAT version internally, so I'll probably migrate that update to here and then add to crates.io at the same time.

**Comment by aikalant** [comment]
I've published the current version, some point soon I will add an updated one compatible with GATs

https://crates.io/crates/capnp_conv

**Comment by p--b** [comment]
Thanks!
